# Bounding Boxes

``bounding_boxes`` summarises a folder of GeoTIFF tiles into a single
GeoPackage of polygon footprints. You can open these geopackages in qgis to visualise these locations.

In [1]:
from shelterbelts.classifications.bounding_boxes import bounding_boxes
from shelterbelts.utils.filepaths import _repo_root

In [2]:
gdf = bounding_boxes(
    str(_repo_root / 'data' / 'multiple_binary_tifs'),
    filetype='.tiff',
    tif_cover_threshold=5
)
gdf

Working on 0/2: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/g2_26729_binary_tree_cover_10m.tiff
Saved: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/data_multiple_binary_tifs_footprints.gpkg

,filename,height,width,crs,geometry,pixels_0,pixels_1,bad_tif,percent_trees
0,g2_26729_binary_tree_cover_10m.tiff,201,201,EPSG:28355,"POLYGON ((1184379.593 6169767.94, 1184379.593 ...",20647,19754,False,48.894829
1,g1_01018_binary_tree_cover_10m.tiff,100,100,EPSG:28354,"POLYGON ((581000 7129000, 581000 7130000, 5800...",8847,1153,False,11.530000

## Changing the size_threshold

Any tif where the height or width doesn't meet this threshold is marked as 'bad_tif'. The percent_trees isn't calculated this time because we didn't provide the 'tif_cover_threshold' parameter (to save computation time).

In [3]:
gdf = bounding_boxes(
    str(_repo_root / 'data' / 'multiple_binary_tifs'),
    filetype='.tiff',
    size_threshold=300,
)
gdf

Working on 0/2: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/g2_26729_binary_tree_cover_10m.tiff
Saved: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/data_multiple_binary_tifs_footprints.gpkg

,filename,height,width,crs,geometry,bad_tif
0,g2_26729_binary_tree_cover_10m.tiff,201,201,EPSG:28355,"POLYGON ((1184379.593 6169767.94, 1184379.593 ...",True
1,g1_01018_binary_tree_cover_10m.tiff,100,100,EPSG:28354,"POLYGON ((581000 7129000, 581000 7130000, 5800...",True

## Changing the cover_threshold

Any tif where the percentage of zeros or ones doesn't meet this threshold is marked as 'bad_tif'.

In [4]:
gdf = bounding_boxes(
    str(_repo_root / 'data' / 'multiple_binary_tifs'),
    filetype='.tiff',
    tif_cover_threshold=20
)
gdf

Working on 0/2: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/g2_26729_binary_tree_cover_10m.tiff
Saved: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/data_multiple_binary_tifs_footprints.gpkg

,filename,height,width,crs,geometry,pixels_0,pixels_1,bad_tif,percent_trees
0,g2_26729_binary_tree_cover_10m.tiff,201,201,EPSG:28355,"POLYGON ((1184379.593 6169767.94, 1184379.593 ...",20647,19754,False,48.894829
1,g1_01018_binary_tree_cover_10m.tiff,100,100,EPSG:28354,"POLYGON ((581000 7129000, 581000 7130000, 5800...",8847,1153,True,11.530000

## Saving Centroids
Include a centroid GeoPackage. This is useful for visualising the spread of small tifs in very zoomed out areas.

In [5]:
gdf = bounding_boxes(
    str(_repo_root / 'data' / 'multiple_binary_tifs'),
    filetype='.tiff',
    save_centroids=True
)

Working on 0/2: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/g2_26729_binary_tree_cover_10m.tiff
Saved: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/data_multiple_binary_tifs_footprints.gpkg
Saved: /home/147/cb8590/Projects/shelterbelts/data/multiple_binary_tifs/data_multiple_binary_tifs_centroids.gpkg